// ---------------------------------------------------------------------------
// Pre-commit hook installer for blocked_paths
// ---------------------------------------------------------------------------
//
// Writes a pre-commit hook into the workspace's .git/hooks/ that rejects
// commits touching any blocked path. Cross-platform: emits a sh script that
// works on POSIX and on Windows under git-bash (which is bundled with
// Git for Windows and is what `git commit` invokes for hooks).
// ---------------------------------------------------------------------------

import * as fs from 'fs/promises';
import * as path from 'path';

/**
 * Install (or refresh) the pre-commit hook in `<workspacePath>/.git/hooks/`.
 * No-op when blockedPaths is empty.
 *
 * Idempotent: re-running with the same patterns overwrites the hook with
 * identical content.
 */
export async function installBlockedPathsHook(
  workspacePath: string,
  blockedPaths: string[],
): Promise<void> {
  if (blockedPaths.length === 0) return;

  const hooksDir = path.join(workspacePath, '.git', 'hooks');
  try {
    const stat = await fs.stat(path.join(workspacePath, '.git'));
    if (!stat.isDirectory()) return;
  } catch {
    return; // not a git repo yet
  }
  await fs.mkdir(hooksDir, { recursive: true });

  const hookPath = path.join(hooksDir, 'pre-commit');
  const script = renderHookScript(blockedPaths);
  await fs.writeFile(hookPath, script, { encoding: 'utf-8', mode: 0o755 });

  // chmod is a no-op on Windows but helpful on POSIX hosts
  try {
    await fs.chmod(hookPath, 0o755);
  } catch {
    // best effort
  }
}

function renderHookScript(blockedPaths: string[]): string {
  // Convert each glob to a grep-E (extended) pattern. We translate `**` → `.*`
  // and `*` → `[^/]*`. Anchors are added so partial matches don't trigger
  // false positives.
  const patterns = blockedPaths.map(globToGrepPattern);
  const grepArg = patterns.map((p) => `'^${p}$'`).join(' -e ');

  return [
    '#!/bin/sh',
    '# Auto-generated by Harmony — enforces guardrails.blocked_paths.',
    '# Edits to listed paths abort the commit. Remove this file to disable.',
    '',
    'BLOCKED=$(git diff --cached --name-only --diff-filter=ACMR | grep -E -e ' + grepArg + ' || true)',
    'if [ -n "$BLOCKED" ]; then',
    '  echo "Harmony guardrail: blocked path(s) in commit:" 1>&2',
    '  echo "$BLOCKED" 1>&2',
    '  exit 1',
    'fi',
    'exit 0',
    '',
  ].join('\n');
}

function globToGrepPattern(glob: string): string {
  let out = '';
  for (let i = 0; i < glob.length; i++) {
    const ch = glob[i];
    if (ch === '*') {
      if (glob[i + 1] === '*') {
        out += '.*';
        i++;
        if (glob[i + 1] === '/') i++;
      } else {
        out += '[^/]*';
      }
    } else if (ch === '?') {
      out += '[^/]';
    } else if ('.+^$(){}[]|\\/'.includes(ch)) {
      // Escape regex specials, keep `/` literal (no escape needed in ERE).
      out += ch === '/' ? '/' : '\\' + ch;
    } else {
      out += ch;
    }
  }
  return out;
}
